name: Build IPA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout del código
      - name: Checkout
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      # Configurar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          dotnet-version: '9.0.x'

      # Restaurar workloads de iOS
      - name: Restore Workloads
        run: dotnet workload restore

      # Restaurar dependencias
      - name: Restore Dependencies
        run: dotnet restore

      # Configurar Xcode (usa versión disponible en runners)
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2.0'

      # Compilar IPA
      - name: Build IPA
        run: dotnet build SpotifyPremium.sln -c Release

      # Publicar artefacto IPA
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SpotifyPremium-IPA
          path: '**/*.ipa'
