name: Build Spotify Premium IPA

on: [push]

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Xcode 26.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build IPA SIN FIRMA (para eSign)
        run: dotnet publish -f net9.0-ios -c Release -p:BuildIpa=true -p:CodesignRequired=false -p:DisableAutomaticSigning=true -p:CodesignKeychain="" -p:CodesignProvision="" -p:CodesignSign="" -p:SigningKey="" -p:ProvisioningProfile=""

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SpotifyPremium
          path: '**/*.ipa'
